### ISSUE TITLE
No internet - send button and other features to be disabled

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1448] opened 2020-08-27 05:23 UTC
Send button to be disabled when there is no internet modal
Review other areas as well which needs to be disabled in case of no internet - create multiple issues if required

**Comment by antuz123** [comment] 2020-11-02 07:27
@cakesoft-swati - a duplicate of another one I just commented on.

**Comment by cakesoft-swati** [comment] 2020-11-06 06:04
-Didn't find any duplicate of this bug.

**Closed** 2020-11-06 06:08 UTC
Labels: 1.3.2
