### ISSUE TITLE
First Login

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5462] opened 2022-02-17 03:23 UTC
1. Skip the password screen when initial onboarding. 

The message on the home page will be that the wallet is not backed up. User can always go and do the backup from there.

**Comment by cakesoft-swati** [comment] 2022-02-18 11:15
- Verified this issue in dev app v2.0.70(439).Password screen is removed but the loader modal is very quick it is visible for less than 1 second.Do we need to remove it as well or what?

**Comment by cakesoft-swati** [comment] 2022-02-21 04:48
- Verified this issue on dev app v2.0.70(440)

**Comment by cakesoft-swati** [comment] 2022-02-22 11:01
- Android Device:It is taking 3/5 seconds to enter into the wallet(Tested on One plus 9R)
- ios device:It is taking 8/10seconds to enter into the wallet(Tested on iphone 7)

**Comment by cakesoft-swati** [comment] 2022-02-24 09:33
- Unable to reproduce it on other devices so closing it for now.

**Closed by cakesoft-swati** 2022-02-24 09:33 UTC
Labels: Fixed, Reopen, Login, 2.0.70
