### ISSUE TITLE
OTP message should be visible on next screen.

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4800] opened 2021-11-22 06:43 UTC
The OTP message should be visible on the screen where a user is about to share QR or link.

The user should be able to copy the OTP to share with the receiver easily

**Comment by antuz123** [comment] 2021-11-22 07:33
We already have a modal that we use in F&F when an encryption key is selected - phone/ email or OTP

**Comment by cakesoft-swati** [comment] 2021-11-23 12:24
Duplicate of #4842

**Closed by cakesoft-swati** 2021-11-23 12:24 UTC
Labels: Gift, 2.07
