### ISSUE TITLE
Receive notification 

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4652] opened 2021-11-07 14:53 UTC
I received sats from Anant. I got the notification saying, "You have a new transaction from Anant." The notification should say, "Received (amount) sats from (friend name)". (Would require coding effort)

![Screenshot_20211107-202011_hexa.jpg](https://user-images.githubusercontent.com/68264080/140650017-00db2452-227c-4732-9b5f-12152712b8ae.jpg)

**Comment by Raheel1258** [comment] 2021-12-02 13:47
Backend blocker. The price (SAT) is not coming in API

**Comment by Vatsal032** [comment] 2022-07-07 09:34
@cakesoft-shashank can you tell if there is a way to fetch the details of the transaction using the transaction ID, so that we can display the amount.

**Comment by cakesoft-shashank** [comment] 2022-07-07 10:01
> @cakesoft-shashank can you tell if there is a way to fetch the details of the transaction using the transaction ID, so that we can display the amount.

No. Transaction details can be included in the notification while sending

**Comment by Vatsal032** [comment] 2022-07-07 12:56
So can you guide about where I can find the code related to sending this notification? @cakesoft-shashank

**Comment by Vatsal032** [comment] 2022-07-13 09:47
@cakesoft-swati  did you make a new transaction and check if the notification is in the same old format? If not please try making a new transaction and let me know if the issue is still active.

**Comment by cakesoft-swati** [comment] 2022-07-13 11:25
@Vatsal032 ,yes I tried it with new transaction and tested on dev app v2.0.80(486)

**Comment by Vatsal032** [comment] 2022-07-13 11:40
@cakesoft-swati the new changes have been merged with the feature/2.0.80 branch. Please check again and let me know if the issue still present.

**Comment by Deveshshankar** [comment] 2022-07-15 08:43
1.I received sats from (Friend Name) . I got the notification saying, "You have a new transaction from ( friend Name)." The notification should say, "Received (amount) sats from (friend name)". (Would require coding effort)

The notification should say, "Received (amount) sats from (friend name)". (Would require coding effort)

attached the images below 

![Screenshot_2022-07-15-14-02-29-19_6ccb4bf936ab2cedd5e025652c6047ae](https://user-images.githubusercontent.com/107177634/179186997-d324d966-cd7c-4752-a568-dac23a21d2f3.jpg)
![Screenshot_2022-07-15-14-06-52-21_6ccb4bf936ab2cedd5e025652c6047ae (1)](https://user-images.githubusercontent.com/107177634/179187619-f7de15d1-8885-4f89-90d6-78a11b032585.jpg)

**Comment by Deveshshankar** [comment] 2022-07-15 10:27
Resolved 
Received Notification in F&F 
![Screenshot_2022-07-15-15-32-01-98_6ccb4bf936ab2cedd5e025652c6047ae](https://user-images.githubusercontent.com/107177634/179205482-906e5917-a6a7-4259-a635-4fd0367e6a89.jpg)
![Screenshot_2022-07-15-15-32-08-80_6ccb4bf936ab2cedd5e025652c6047ae](https://user-images.githubusercontent.com/107177634/179205591-a50ac90e-4bdd-41b1-96c6-59033b0e5185.jpg)

**Closed by Deveshshankar** 2022-07-15 10:27 UTC
Labels: Status: fixed✅, UAI💬, 2.0.80
