### ISSUE TITLE
UI issue on Donation Account>2FA screen

### ISSUE THREAD

**Issue by cakesoft-devika** [bithyve/hexa#3264] opened 2021-04-30 08:11 UTC
For Donation account, Button and text hide when confirming 2FA with incorrect OTP

![Screenshot_2021-04-29-20-47-17-924_io hexawallet hexa staging](https://user-images.githubusercontent.com/75297509/116666997-46fd9580-a9b9-11eb-9782-8ae9e01285f3.jpg)

**Comment by AliMeer** [comment] 2021-04-30 08:24
Duplicate of https://github.com/bithyve/hexa/issues/2697

**Closed by AliMeer** 2021-04-30 08:24 UTC
Labels: 1.7.0
