### ISSUE TITLE
Wallet Backup scheme 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#3904] opened 2021-07-30 18:18 UTC
Choose an encryption option - language

The language used on the wallet backup screen while setting up the wallet is not clear. It should be more about choosing an encryption option. Also need to be clear what is being backed up. 

Suggest better language.

**Comment by summikhan11** [comment] 2021-08-01 18:56
https://xd.adobe.com/view/0aef8043-d951-4d0a-9a97-b7b2e16ffdbc-5fbc/screen/5d1acb75-2ed2-4c9e-889a-3b5a50fb6f8c/

**Comment by cakesoft-shashank** [comment] 2021-08-04 10:50
@cakesoft-rohit please check referenced commit

**Comment by cakesoft-swati** [comment] 2021-08-09 11:09
Duplicate of #3854

**Closed by cakesoft-swati** 2021-08-09 11:09 UTC
Labels: NFR, 1.9.0
