### ISSUE TITLE
Send button on Test account not responsive - iOS

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1296] opened 2020-08-07 06:06 UTC
Open the app afresh. Go to test account and try clicking the send.

do it 2-3 times by closing and opening the app after a dely.

**Comment by abdulmuneer22** [comment] 2020-08-07 11:44
@Arpanjainson , could you please add a video of it ? not able to reproduce it consistently

**Comment by abdulmuneer22** [comment] 2020-09-18 11:46
Duplicate https://github.com/bithyve/hexa/issues/1296

**Comment by abdulmuneer22** [comment] 2020-09-18 11:47
Duplicate of https://github.com/bithyve/hexa/issues/1240

**Closed by abdulmuneer22** 2020-09-18 11:47 UTC
Labels: 1.1.3, NFR
