### ISSUE TITLE
Sender and receiver for incoming and outgoing transactions.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#4397] opened 2021-09-20 04:55 UTC
- For incoming transactions it is the sender. For the outgoing transaction it is the receiver. 
![incomingoutgoing](https://user-images.githubusercontent.com/62699947/133958365-15188f3e-b4e4-4224-9a57-9155bff1b2a8.jpg)

- Same for gift, it should be marked as a gift for this outgoing transaction.
![gifttxn](https://user-images.githubusercontent.com/62699947/135050742-74487635-1065-4c5a-86b9-ff4b50e44040.jpg)

**Comment by cakesoft-shashank** [comment] 2021-10-04 07:54
Duplicate of #4080

**Comment by cakesoft-swati** [comment] 2021-11-01 09:21
- Verified this issue on dev app v2.0.1(373)

**Closed** 2021-11-03 14:47 UTC
Labels: S&R, fixed, 2.01
