### ISSUE TITLE
QR scanner.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1782] opened 2020-10-09 07:42 UTC
-After using the QR scanner (main menu bottom middle button) and hiding it’s “tab” the camera stays toggled on for no reason. -Only when the app is open, goto different app it’s gone, switch back in and camera toggles on.

**Comment by CypherPoet** [comment] 2020-10-16 22:06
Ideally, this can be tackled as part of https://github.com/bithyve/hexa/issues/1833

**Comment by CypherPoet** [comment] 2020-10-16 22:09
Closing as a duplicate of #1833.

**Closed by CypherPoet** 2020-10-16 22:09 UTC
Labels: 1.3.1, APP
