### ISSUE TITLE
Address book permission 

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#1533] opened 2020-09-13 04:18 UTC
specs link "Information Screen - Access to AddressBook"

**Comment by AliMeer** [comment] 2020-11-03 08:20
@cakesoft-swati this can be closed as it’s a duplicate of https://github.com/bithyve/hexa/issues/1781

**Comment by AliMeer** [comment] 2020-11-06 11:54
Closing, this will be done as part of https://github.com/bithyve/hexa/issues/1524

**Closed by AliMeer** 2020-11-06 11:54 UTC
Labels: 1.3.1, UX
