### ISSUE TITLE
The buttons are not very responsive.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1107] opened 2020-07-21 06:48 UTC
-The buttons are still not very responsive and the spinning wheel is coming in the screen. 
-It should come on the top.
![spinningwheel](https://user-images.githubusercontent.com/62699947/88022058-3546b200-cb4c-11ea-9ee3-1e25ff2c505f.jpg)

**Comment by abdulmuneer22** [comment] 2020-08-07 05:04
For this converting accounts screen to a class or reducing re-renders will help us improve this

**Comment by abdulmuneer22** [comment] 2020-09-18 11:47
Duplicate of https://github.com/bithyve/hexa/issues/1240

**Closed** 2020-09-18 11:47 UTC
Labels: 1.1.3, NFR
