### ISSUE TITLE
PDF sharing failed

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#2406] opened 2021-01-04 06:40 UTC
On iOS FI PDF sharing is failing. User reported and also able to recreate

**Comment by Parsh** [comment] 2021-01-04 10:06
Tested it on iOS simulator(FI), it worked alright for the bottom two sharing options(wasn't able to test the Sending email option due to sim).


![Simulator Screen Shot - iPhone 11 - 2021-01-04 at 15 33 32](https://user-images.githubusercontent.com/17980466/103523855-8d773380-4ea2-11eb-9cfb-bb2baa50da65.png)


![Simulator Screen Shot - iPhone 11 - 2021-01-04 at 15 35 39](https://user-images.githubusercontent.com/17980466/103523857-8e0fca00-4ea2-11eb-95a2-fd1db8bcf529.png)


![Simulator Screen Shot - iPhone 11 - 2021-01-04 at 15 33 17](https://user-images.githubusercontent.com/17980466/103523845-89e3ac80-4ea2-11eb-856a-e1570211248a.png)

**Comment by Parsh** [comment] 2021-01-04 10:07
If we need to test it on a real device then it would be a good idea to re-assign this issue.

**Comment by antuz123** [comment] 2021-01-04 12:46
Under what circumstances is it failing? 
1. Special characters? 
2. Some other condition?

**Comment by AliMeer** [comment] 2021-01-04 19:00
@Arpanjainson I have tried this a few times on simulator and Device and not able to reproduce.
Steps: Delete existing app>>Install App>>Follow wallet setup journey>>Click Manage Backup As soon as possible on Home Screen>>Click first personal copy share as soon as possible on Manage backup screen>>Click Email share as soon as possible on Personal copy share screen

**Comment by AliMeer** [comment] 2021-01-05 00:26
@Arpanjainson @cakesoft-swati can we test this on Android as well please?

**Comment by cakesoft-swati** [comment] 2021-01-06 09:45
-Unable to reproduce this on Android as well.
-Tested on Dev app v1.4.1(192)

**Closed by cakesoft-swati** 2021-01-06 09:45 UTC
Labels: 1.4.1, B-H-R, fixed
