### ISSUE TITLE
Transactions.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1865] opened 2020-10-22 05:04 UTC
-This screen is to explain that the test account showed funded but the txn did not show up.. other accounts when funded manually via faucets worked fine.
![Image from iOS (3)](https://user-images.githubusercontent.com/62699947/96826927-0e9d5d80-1452-11eb-8b9d-5d2b80e3d152.png)

**Comment by Parsh** [comment] 2020-10-28 08:56
Duplicate of #1864

**Comment by antuz123** [comment] 2020-10-28 10:10
Coxed as per the duplicate.

**Closed by antuz123** 2020-10-28 10:10 UTC
Labels: 1.3.0, TXNS
