### ISSUE TITLE
Unable to create a Wyre account using Home > Buy option.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2570] opened 2021-01-25 05:45 UTC
[Only on Android device.Tested on SAMSUNG Galaxy A50].
-Unable to open Accout details page by clicking on Buy>Buy using ApplePay or Debit Card.
[Able to create Wyre account by using Add New option.]

**Comment by cakesoft-swati** [comment] 2021-01-27 12:54
Sometimes it opens on clicking multiple times(8/10 times), or I have to long press it.
-Tested on Dev app v1.4.2(210)

**Comment by AliMeer** [comment] 2021-01-27 17:33
Closing this as the issue is related to the buy menu item not being clicked. Tracking this issue here https://github.com/bithyve/hexa/issues/2599

**Comment by AliMeer** [comment] 2021-01-27 17:33
Closing this as the issue is related to the buy menu item not being clicked. Tracking this issue here https://github.com/bithyve/hexa/issues/2599

**Comment by AliMeer** [comment] 2021-01-27 17:35
Closing this as the issue is related to the buy menu item not being clicked. Tracking this issue here https://github.com/bithyve/hexa/issues/2599

**Closed by AliMeer** 2021-01-27 17:35 UTC
Labels: 1.4.3, Reopen, UX
