### ISSUE TITLE
Alignment is not correct.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2557] opened 2021-01-22 06:49 UTC
-Not aligned at all.
<img width="375" alt="51E9020F-2E17-4F03-A32F-C0483579440F" src="https://user-images.githubusercontent.com/62699947/105456890-f553b980-5cab-11eb-8b0e-a30a8c33ea96.png">

**Comment by CypherPoet** [comment] 2021-01-22 16:37
I'm a bit confused about what this issue is calling for. Right now, the icon and the text are being set as a single center-justified group. Is this issue calling for them to be left-aligned, the just having the icon be left-aligned while the text remains centered? 

(@Arpanjainson @antuz123 @AliMeer)

**Comment by AliMeer** [comment] 2021-01-22 16:43
There 3 images will illustrate the issue. The send button content is not always centre aligned. It’s should be like the screen shot with the green check mark.

![8B4F3328-8FB2-49C3-87A8-50096A93B7AE](https://user-images.githubusercontent.com/7535475/105519126-fa772f80-5cd0-11eb-8207-a5a98941f656.jpeg)
![C4434950-8341-4FFE-B0FF-285BC2BA4CC0](https://user-images.githubusercontent.com/7535475/105519141-fe0ab680-5cd0-11eb-8afb-25eba7b2851d.jpeg)
![560D4AB2-3A49-4547-8B79-6C89E785E3D4](https://user-images.githubusercontent.com/7535475/105519146-ff3be380-5cd0-11eb-9d96-2c3a857b2a01.jpeg)

**Comment by CypherPoet** [comment] 2021-01-22 16:50
The designs [here](https://xd.adobe.com/view/a9aaad23-c5ea-4067-8734-cf64073bca02-fcf9/screen/988840e5-b355-47b8-8b47-6d7f5a19b49f/specs/) are showing all of the content (image and text) being center aligned and justified as a group.

<img width="455" alt="Screen Shot 2021-01-22 at 10 49 49 AM" src="https://user-images.githubusercontent.com/46851636/105519898-a1db6e80-5c9f-11eb-8e2f-e420c652fd3d.png">

Are these the latest specs? (@Arpanjainson)

**Comment by AliMeer** [comment] 2021-01-22 17:07
> The designs [here](https://xd.adobe.com/view/a9aaad23-c5ea-4067-8734-cf64073bca02-fcf9/screen/988840e5-b355-47b8-8b47-6d7f5a19b49f/specs/) are showing all of the content (image and text) being center aligned and justified as a group.
> 
> <img alt="Screen Shot 2021-01-22 at 10 49 49 AM" width="455" src="https://user-images.githubusercontent.com

> The designs [here](https://xd.adobe.com/view/a9aaad23-c5ea-4067-8734-cf64073bca02-fcf9/screen/988840e5-b355-47b8-8b47-6d7f5a19b49f/specs/) are showing all of the content (image and text) being center aligned and justified as a group.
> 
> <img alt="Screen Shot 2021-01-22 at 10 49 49 AM" width="455" src="https://user-images.githubusercontent.com/46851636/105519898-a1db6e80-5c9f-11eb-8e2f-e420c652fd3d.png">
> 
Yes this is how it should be. In this image the white space left of send icon on the button and the white space left of the receive icon on the button is the same, but that’s not the case in the image shown in the issue.

**Comment by CypherPoet** [comment] 2021-01-22 18:14
Right, the reason for what's captured in the issue is because with width of the content is going to vary according to the text for the transaction fee. If we don't show a transaction fee for one or the other, it's going to have more spacing than the button with the fee displayed.

**Comment by AliMeer** [comment] 2021-01-24 18:39
I suspect this was caused by this commit: https://github.com/bithyve/hexa/commit/fb3e9dee10694d346eb9c73b9ad214357939bbfd
Which was a change to fix https://github.com/bithyve/hexa/issues/2527

**Comment by AliMeer** [comment] 2021-01-27 19:21
Moving this to 1.4.2 as it got fixed as part of another similar ticket.

**Closed** 2021-02-01 13:20 UTC
Labels: 1.4.2, UX, fixed
