### ISSUE TITLE
UI Changes for Sharing QR Codes

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#2400] opened 2021-01-04 05:36 UTC
-All these screens should show the QR here and link as a secondary option. This applies to
1. F&F request screen
2. Receive screen
3. Keeper request screen
4. Keeper reshare screen
![File (22)](https://user-images.githubusercontent.com/62699947/103504253-e46a1200-4e7c-11eb-9ef8-54ae85c7a2b4.jpg)

**Comment by CypherPoet** [comment] 2021-01-04 17:39
@antuz123 @cakesoft-swati I'm not entirely clear about what's being asked for here. Mainly, how is "should show the QR here and link as a secondary option" different than the footer buttons shown above?

**Comment by antuz123** [comment] 2021-01-04 17:43
This needs UX first @Arpanjainson

**Comment by Arpanjainson** [comment] 2021-01-06 12:58
@antuz123 @CypherPoet  the screens have been mocked already and are in prototype - UX mentioned issues with spec links not being updated - look for following screens on the prototype
Accounts – Receive – Add as trusted contact – QR/Link
Add – Add Contact – Send Request – QR/Link
Recovery Secrets – Trusted Contacts – Request Share

**Comment by antuz123** [comment] 2021-01-08 09:05
See 2415. Seems to be a duplicate.

**Comment by CypherPoet** [comment] 2021-01-26 16:41
Duplicate of #2415

**Closed by CypherPoet** 2021-01-26 16:41 UTC
Labels: 1.4.3, UX
