### ISSUE TITLE
Lightning on Hexa logo

### ISSUE THREAD

**Issue by antuz123** [bithyve/hexa#5397] opened 2022-02-08 12:27 UTC
On logo and splash screen?

**Comment by summikhan11** [comment] 2022-02-15 11:23
https://github.com/bithyve/hexa/issues/5413 - same issue.

do we do this now, or when lightning is fully incorporated?

**Comment by cakesoft-shashank** [comment] 2022-02-15 11:31
Duplicate of #5413

**Closed** 2022-02-17 05:37 UTC
Labels: 2.0.70, Operate
