### ISSUE TITLE
Edit contact details (of a F&F)

### ISSUE THREAD

**Issue by AliMeer** [bithyve/hexa#3409] opened 2021-05-18 23:21 UTC
Edit contact details (of a F&F)
Once F&F is added, the user should be able to change the contact name if they want. The edit button will give them a way to either associate a contact or just input a name.
Friends & Family – Contact Details

**Comment by antuz123** [comment] 2021-06-15 05:37
The edit will be from the contact details page. And when initiated, the user can associate a new contact or fill in manually (just enter name and second name)

**Comment by cakesoft-rohit** [comment] 2021-07-09 09:40
Friends & Family – Contact Details – Edit
Friends & Family – Contact Details – Edit – Associate
in
Specs Link: https://xd.adobe.com/view/6e89fcde-5787-4d1a-a1ba-c284e770fdad-3bda/

**Comment by summikhan11** [comment] 2021-07-15 03:44
Specs Link: https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/2647eb6d-ef18-47c2-8c54-3a063a344b71/

**Comment by antuz123** [comment] 2021-07-15 05:47
Use the one with Associate Contact

**Comment by cakesoft-rohit** [comment] 2021-07-30 13:07
@summikhan11 https://xd.adobe.com/view/e8259038-6a8a-4b4f-b88f-780e311438a5-bd76/screen/2647eb6d-ef18-47c2-8c54-3a063a344b71/
Need 'Associate contact' option in edit contact

**Comment by cakesoft-rohit** [comment] 2021-07-30 13:12
@summikhan11  ![Simulator Screen Shot - iPhone 11 - 2021-07-30 at 18 38 59](https://user-images.githubusercontent.com/74172232/127657474-ee2f758c-526c-4766-839d-562b0ebd0d01.png)
Please provide a screen to display edit button in contact detail screen

**Comment by cakesoft-rohit** [comment] 2021-09-01 05:23
duplicate of #3556

**Closed by cakesoft-rohit** 2021-09-01 05:23 UTC
Labels: F&F, 1.9.5
