### ISSUE TITLE
Recovery Flow text change

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#4698] opened 2021-11-16 13:17 UTC
“If you previously had Hexa 2.0, you can recover using the Recovery Keys with this option
(If you are trying to migrate from Hexa 1.0 to Hexa 2.0, please read how to do here)”

The word "here" above should be a hyperlink to this: https://hexawallet.io/faq/

![Text Changes Required](https://user-images.githubusercontent.com/68264080/141990871-3f06bda5-8771-4295-af3f-65c0fc5c2dc0.jpg)

**Comment by cakesoft-shivani** [comment] 2021-11-17 05:19
This is duplicate of #4691

**Comment by cakesoft-shivani** [comment] 2021-11-17 05:20
This is duplicate of #4691

**Comment by cakesoft-shivani** [comment] 2021-11-17 05:20
This fixed will be available in next build

**Comment by cakesoft-swati** [comment] 2021-11-19 14:00
- Verified this issue on staging app v2.0.5(377)

**Closed by cakesoft-swati** 2021-11-19 14:00 UTC
Labels: NFR, fixed, 2.05
