### ISSUE TITLE
Change currency crashed in staging 84 upgraded from v65

### ISSUE THREAD

**Issue by Arpanjainson** [bithyve/hexa#1262] opened 2020-08-03 20:26 UTC

**Comment by abdulmuneer22** [comment] 2020-08-05 16:25
Note :

v65 PR : 354431e0

**Comment by abdulmuneer22** [comment] 2020-08-07 07:01
Duplicate of https://github.com/bithyve/hexa/issues/1268

**Closed** 2020-08-07 07:01 UTC
Labels: 1.2
