### ISSUE TITLE
Notification not updating after lvl3 is done

### ISSUE THREAD

**Issue by ASN-BitHyve** [bithyve/hexa#5016] opened 2021-12-07 12:32 UTC
![IMG_20211207_180015_193.jpg](https://user-images.githubusercontent.com/68264080/145029613-0e92e921-02b5-426f-9118-e48fcf5296e7.jpg)

**Comment by cakesoft-swati** [comment] 2021-12-07 13:24
Duplicate of #4887

**Closed by cakesoft-swati** 2021-12-07 13:24 UTC
