### ISSUE TITLE
Issues while entering OTP.

### ISSUE THREAD

**Issue by cakesoft-swati** [bithyve/hexa#1889] opened 2020-10-27 05:24 UTC
-Not moving to the next box quickly, after a while. 
-Allowing multiple entries in one box. Should allow only one. Sometimes the keyboard covers the text boxes.
![notmoving](https://user-images.githubusercontent.com/62699947/97260278-a16b3d00-1842-11eb-8c5e-b9e1b04c4e1b.jpg)

**Comment by Parsh** [comment] 2020-10-28 08:50
Duplicate of #1891

**Closed** 2020-11-02 06:59 UTC
Labels: 1.3.1, F&F, UX
